'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace XpoWebApplication


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxFormLayout1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

		''' <summary>
		''' navigateComboBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected navigateComboBox As Global.DevExpress.Web.ASPxComboBox

		''' <summary>
		''' ASPxFormLayout1_E2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxFormLayout1_E2 As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' ASPxFormLayout1_E3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxFormLayout1_E3 As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' ASPxFormLayout1_E4 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxFormLayout1_E4 As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' ASPxFormLayout1_E5 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxFormLayout1_E5 As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' ASPxButton1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxButton1 As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' XpoDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected XpoDataSource1 As Global.DevExpress.Xpo.XpoDataSource

		''' <summary>
		''' XpoDataSource2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected XpoDataSource2 As Global.DevExpress.Xpo.XpoDataSource
	End Class
End Namespace
